config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [] do
    resources :opinions, only: [:new, :create]
  end

  get 'topics/opinions/thank-you' => 'opinions#thank_you', as: :thank_you_opinions
  get 'topics/opinions/clear-session' => 'opinions#clear_session', as: :clear_session_opinions
  root 'opinions#new'
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
	belongs_to :topic
	validates :content, :topic, presence: true
	validates :agree, inclusion: [false, true]
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :opinions
	validates :content, presence: true

	def self.next_incomplete_topic(list_completed_topics)
		Topic.where.not(id: list_completed_topics).first
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
	before_action :redirect_if_topic_is_conpleted, only: [:new]
	def new
		@opinion = current_topic.opinions.new
	end

	def create
		@opinion = current_topic.opinions.build(opinion_params)
		if @opinion.save
			mark_topic_as_completed
			redirect_to_next_topic
		else
			render :new
		end
	end

	def clear_session
		session[:completed_topics] = nil
		redirect_to_next_topic
	end

	private

		def current_topic
			if topic_id.present?
				Topic.find(topic_id)
			else
				Topic.first
			end
		end

		def topic_id
			params[:topic_id]
		end

		def opinion_params
			params.require(:opinion)
				.permit(:content, :agree)
		end

		def completed_topics
			session[:completed_topics] ||= []
		end

		def mark_topic_as_completed
			completed_topics << topic_id.to_i
		end

		def redirect_if_topic_is_conpleted
			redirect_to_next_topic if completed_topics.include? current_topic.id
		end

		def redirect_to_next_topic
			next_topic = Topic.next_incomplete_topic(completed_topics)

			if next_topic.present?
				redirect_to new_topic_opinion_url(topic_id: next_topic.id)
			else
				redirect_to thank_you_opinions_url
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
	head
	  title Opinionation
	  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
	  = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Work+Sans'
	  = javascript_include_tag 'application', 'data-turbolinks-track' => true
	  = csrf_meta_tags
	body
		.container
			.row
				.col-lg-9
					= yield
				.col-lg-3
					= render 'shared/side_bar'

app/views/opinions/_side_bar.html.slim
.sidebar
	.panel.panel-default
		.panel-body
			.image
				= image_tag('avt.png')
		.panel-footer
			p.copyright 2015 &copy; Copyright	

app/views/opinions/new.html.slim
- topic = @opinion.topic

#opinions-new
	.panel.panel-default
		.panel-body
			.topic				
				p.topic-no Topic ##{ topic.id }
			
				h1.topic-content = topic.content

			.opinion-form
				= simple_form_for @opinion, url: topic_opinions_path(topic_id: topic.id) do |f|
					= f.input :agree,
						label: false,
						as: :radio_buttons,
						error: false
					= f.input :content,
						label: false,
						placeholder: 'Enter your opinion here',
						error: false
					= render 'shared/error_messages', object: f.object
					= f.button :submit,
						class: "btn-primary opinion-button"

app/views/opinions/thank_you.html.slim
#opinions-thank-you
	.panel.panel-default
		.panel-body
			h1.thank-you-message
				| Thank you for submitting your opinion
			.clear-session = link_to "Clear session", clear_session_opinions_path, class: "btn btn-default"

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    ul
      - object.errors.full_messages.each do |msg|
        li
          | * #{msg}

app/views/shared/_side_bar.html.slim
.sidebar
	.panel.panel-default
		.panel-body
			.image
				= image_tag('avt.png')
		.panel-footer
			p.copyright 2015 &copy; copyright